### ISSUE TITLE
Gallery does not complete it's loading on Safari

### ISSUE THREAD

**Issue by NVLudwig** [unoplatform/Uno.Gallery#1066]
Gallery hangs on splash screen when loading from safari, work fine in Chrome

## Current behavior
![image](https://github.com/unoplatform/Uno.Gallery/assets/29584087/2c2a0398-974c-4cce-b21f-abad1bc5d4af)

`fail: Uno.UI.Dispatching.CoreDispatcher[0]
      Dispatcher unhandled exception
System.Reflection.TargetInvocationException: Arg_TargetInvocationException
---> System.InvalidOperationException: Cannot locate resource from 'ms-resource:///Files/m:-appx:///Microsoft.UI.Xaml/Themes/themeresources_v2.xaml'
   at Microsoft.UI.Xaml.Controls.XamlControlsResourcesV2..ctor()
   at Uno.Gallery.Wasm.__Resources._SamplePageLayout_763a1a6ef7aae7f96058cffc4fe315b1_SamplePageLayoutRDSC1.Build(Object __ResourceOwner_1)
   at Uno.Gallery.Wasm.GlobalStaticResources.ResourceDictionarySingleton__SamplePageLayout_763a1a6ef7aae7f96058cffc4fe315b1.<>c.<Get_5>b__9_1(Object __owner)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   Exception_EndOfInnerExceptionStack
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Uno.Gallery.App.ShellNavigateTo(Sample sample, Boolean trySynchronizeCurrentItem)
   at Microsoft.UI.Xaml.Application.Initialize()
   at Uno.UI.Dispatching.CoreDispatcher.InvokeOperationSafe(UIAsyncOperation operation)`

## Expected behavior

load and run normally

## Environment

Safari Version 16.6 (18615.3.12.11.2)

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by NVLudwig** [comment]
@agneszitte reports it works for her in version (16.5.2)

**Comment by jeromelaban** [comment]
macOS Sonoma is required when running in M1/arm64 devices (Safari 17.2.1)

**Comment by jeromelaban** [comment]
I'm not sure if we can, because we need to detect that we're running on arm64. Safari does not report this in a reliable way, for what I can tell...

**Comment by NVLudwig** [comment]
BTW the Figma plugin was not working on Safari either so I tried an upgrade to Sonoma thanks to you and now the plugin works as well. IDK how you do it Jerome there is no way I would have guessed it was because of my Processor+OS combo as everything was working on Chrome. Is this documented somewhere?

**Comment by jeromelaban** [comment]
You're welcome ;) 

It's not explicitly documented at this time, aside from https://github.com/unoplatform/uno/issues/13591, but we have to build some status page for that kind of issues.
