### ISSUE TITLE
[ShadowContainer][Wasm] Shadow Builder - Delay visible when adding/removing shadows or switching to Light/Dark

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/Uno.Gallery#976]
## Current behavior

Shadow Builder - Delay visible when adding/removing shadows or switching to Light/Dark for Wasm 
(should be carefully tested on the other platforms)

## Expected behavior

No delay visible

## How to reproduce it (as minimally and precisely as possible)

- Open Uno Gallery APP
- Click Burger Menu on the left top right (if the menu is not already opened)
- Click "ShadowContainer" from the "Toolkit" section.
- Use the Shadow Builder
  -  Add/Remove shadows
  - Switch the app theme from Light to Dark or Dark to Light (using the ToggleSwitch in the menu)
Notice a delay when the Shadow Builder shadows or elements are drawn

#### Adding/removing shadows

https://github.com/unoplatform/Uno.Gallery/assets/16295702/956801ee-e90e-4ac6-bff7-a30a4bc13257

#### Switching Theme Light <-> Dark

https://github.com/unoplatform/Uno.Gallery/assets/16295702/db1ca867-8d57-45ab-b096-d98cc79a6e0d

## Environment

Nuget Package: Uno.Toolkit

Package Version(s): 4.2.22

Affected platform(s):

- [X] WebAssembly
- [?] Other platforms (need to be tested as well)

Visual Studio:

- [X] 2022 (version: 17.7.3)

**Comment by rafael-rosa-knowcode** [comment]
When I upgraded SKXamlCanvas to SKSwapChainPanel using a hardware accelerator, I identified a few issues.

1 -
Speed isn't much better than using software.

See Add new items


https://github.com/unoplatform/Uno.Gallery/assets/116665025/01d13062-73f6-4bf1-bb71-002b6115cb51


See Change Theme.


https://github.com/unoplatform/Uno.Gallery/assets/116665025/2f0c0f9d-aa61-441f-95ec-697a34498019


2- 
When we start the page loading more the 15 (not a precise number) shadows on the page not a single image load, and we get the erro about the Loop on the Javascript.

![image](https://github.com/unoplatform/Uno.Gallery/assets/116665025/426824ff-2a88-418c-9bae-471be4e53125)

Erro.
```
dotnet.js:5 Uncaught    at SkiaSharp.Views.Windows.SKSwapChainPanel.RenderFrame() in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Wasm\SKSwapChainPanel.Wasm.cs:line 111
   at SkiaSharp.Views.Windows.SKSwapChainPanel.RenderFrame(Object instance) in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.Wasm\SKSwapChainPanel.Wasm.cs:line 94
   at SkiaSharp.Views.Windows.SKSwapChainPanel.__Wrapper_RenderFrame_987524064(JSMarshalerArgument* __arguments_buffer) in D:\a\1\s\source\SkiaSharp.Views.Uno\SkiaSharp.Views.Uno.WinUI.Wasm\Microsoft.Interop.JavaScript.JSImportGenerator\Microsoft.Interop.JavaScript.JSExportGenerator\JSExports.g.cs:line 17
undefined
```

3-
Cache do not work. 
When we use the snapshot from the Cache on the SKSwapChainPanel, we just update the last one.. and the othrer do not work well.
 
![image](https://github.com/unoplatform/Uno.Gallery/assets/116665025/4927e83b-8f43-4a14-9c3f-62194a9f7ada)

**Comment by roubachof** [comment]
Don't think we can use hardware accelerated canvas due to its limitations.

**Comment by jeromelaban** [comment]
Thanks for all the updates. If the delay is still present with hardware acceleration (regardless of the limitations), it means that there are other parts at play that need to be identified. It would be interesting to have key performance metrics that show where the time is spent. For instance Skia spends about 500ms rendering a surface here:

![image](https://github.com/unoplatform/Uno.Gallery/assets/5839577/51a753cf-713a-4fdf-974f-af1ef635863f)

It may be a normal behavior, or something completely different.

It would also be interesting to avoid scheduling too many updates (which makes the progressing effect we're seeing), or having none at all if possible, as it shows patterns like this:

![image](https://github.com/unoplatform/Uno.Gallery/assets/5839577/3c525d9d-971b-4c9d-8ee4-e05713f6512f)

**Comment by rafael-rosa-knowcode** [comment]
@jeromelaban 
@roubachof 

Doing tests I noticed that PaintSurface happens after updating the resizing. 
What is generating the perception of delay.
One option would be, when updating the resizing, if the canvas already exists, just updating the canvas without needing to use the PaintSurface event. This way, this would happen immediately after (and in the visual perception of being together) the content size update. 

And over time, even remove layout invalidation when the element changes size (avoiding scheduling too many updates )
Would this be a solution for this case?

**Comment by roubachof** [comment]
@jeromelaban @rafael-rosa-knowcode @agneszitte 

Well if the element changes size, we must invalidate the shadows since the shadows sizes must also be updated.
Also, there is already some code to test if we need to repaint our canvas (if the shadows have same properties than before and the same size, they are no repainted).
Issue was because of a bad comparison (comparing records through interface), the method "NeedsRepaint" was always retuning true, causing unecessaries layout passes.

This is fixed by this PR: https://github.com/unoplatform/uno.toolkit.ui/pull/830

Now this unnecessaries repaint was covering another bug: when the skia canvas size changes, it clears the canvas.
I fixed the bug and will force push to my PR this afternoon.
After this PR is merged we could see if it already improves this issue.

**Comment by roubachof** [comment]
@jeromelaban @agneszitte 
Seems like the repaint issue (aka 2 bugs making the component work), is not helping with the performance in wasm....
Do you want me to try to improve the performance with the same PR?
Can try to merge some invalidations (there are content size and skia canvas size now)

**Comment by rafael-rosa-knowcode** [comment]
@jeromelaban  @roubachof  @agneszitte , 
in terms of optimizing PaintSurface calls, it seems that there are two calls that are redundant (one on the call InvalidateShadows and te second on the natural render phase), so they generate the delay effect in wasm. Because they are called twice, with different sizes.
By removing the duplicate calls it seems that the wasm delay has become much better.
However, the page still takes a long time to load and the first change takes a long time to process. Are these items to be addressed in this issue?

https://github.com/unoplatform/Uno.Gallery/assets/116665025/71fe2295-84f9-4eb2-8b67-df60ec842fdb

PR for validation https://github.com/unoplatform/uno.toolkit.ui/pull/838

**Comment by rafael-rosa-knowcode** [comment]
@agneszitte 
During testing this issue I noticed that when resizing (on wasm) the screen the cache applies to the wrong definition.
If we go from a canvas with 150% resolution to one with 100%, the background image becomes small.
If we go from an 80% resolution to a 100% resolution, the background image becomes large.


https://github.com/unoplatform/Uno.Gallery/assets/116665025/fea2c954-e771-473d-acf1-6f8ddcdae8cb

**Comment by roubachof** [comment]
@rafael-rosa-knowcode please create a new issue for the cache/resolution bug

**Comment by roubachof** [comment]
will try to optimize invalidations in https://github.com/unoplatform/uno.toolkit.ui/pull/830

**Comment by roubachof** [comment]
I did some search on this, because I thought the issue was about the shadows "jumping".
I thought the jumping was due to the way invalidation messages are dispatched to JS on WASM.
But it seems it's *maybe* not the case.
After profiling through Chrome, displaying log messages, this jumping just seems to be some glitches due to resizing child + repositioning canvas.
I don't think there is much to be done here....

For the delay, it's just that shadows are costly and wasm is not performant.
In this sample there are a lot of shadows displayed due to neumorphism, and this is costly.
It could be improved a lot by: https://github.com/unoplatform/uno.toolkit.ui/issues/695
But it will be a hard task to do...


ANNEXE 1: the lost case of the jumpy shadows

So it seems that on WASM, skia canvas painting method is not called directly after the skia canvas `Invalidate` call.
When we click on the Add button int the uno toolkit samples here what happens on windows:

# Windows

## Click on Add button

```
[ShadowContainer] Canvas set left: -155, top: -111
[ShadowContainer] InvalidateShadows
[ShadowContainer] SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 324, CornerRadius = 20,20,20,20 }
[ShadowContainer] Canvas set left: -155, top: -140,25
[ShadowContainer] InvalidateShadows
[ShadowContainer] SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 441, CornerRadius = 20,20,20,20 }
```

## Click on Remove button

```
[ShadowContainer] Canvas set left: -155, top: -140,25
[ShadowContainer] InvalidateShadows
[ShadowContainer] SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 441, CornerRadius = 20,20,20,20 }
[ShadowContainer] Canvas set left: -155, top: -111
[ShadowContainer] InvalidateShadows
[ShadowContainer] SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 324, CornerRadius = 20,20,20,20 }
```

We can see that the painting is done right after the invalidation.
But in WASM:

# WASM

## Click on Add button

```
dotnet.js:2560 [ShadowContainer] 15:27:26.394 : Canvas set left: -155, top: -111
dotnet.js:2560 [ShadowContainer] 15:27:26.394 : InvalidateShadows from OnShadowCollectionChanged
dotnet.js:2560 [ShadowContainer] 15:27:26.694 : Canvas set left: -155, top: -140,25
dotnet.js:2560 [ShadowContainer] 15:27:26.694 : InvalidateShadows from OnContentSizeChanged
dotnet.js:2560 [ShadowContainer] 15:27:26.712 : SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 441, CornerRadius = TopLeft: 20, TopRight: 20, BottomRight: 20, BottomLeft: 20 }
dotnet.js:2560 [ShadowContainer] 15:27:26.820 : SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 441, CornerRadius = TopLeft: 20, TopRight: 20, BottomRight: 20, BottomLeft: 20 }
```

## Click on Remove button

```
dotnet.js:2560 [ShadowContainer] 15:29:51.717 : Canvas set left: -155, top: -140,25
dotnet.js:2560 [ShadowContainer] 15:29:51.717 : InvalidateShadows from OnShadowCollectionChanged
dotnet.js:2560 [ShadowContainer] 15:29:51.726 : Canvas set left: -155, top: -111
dotnet.js:2560 [ShadowContainer] 15:29:51.726 : InvalidateShadows from OnContentSizeChanged
dotnet.js:2560 [ShadowContainer] 15:29:51.745 : SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 324, CornerRadius = TopLeft: 20, TopRight: 20, BottomRight: 20, BottomLeft: 20 }
dotnet.js:2560 [ShadowContainer] 15:29:51.800 : SKIA Painting: CornerRadiusRectShadowShapeContext { Width = 500, Height = 324, CornerRadius = TopLeft: 20, TopRight: 20, BottomRight: 20, BottomLeft: 20 }
```
